/***************************************************************************
 *   Copyright (C) 2008 by Ralf Kaestner                                   *
 *   ralf.kaestner@gmail.com                                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#ifndef CONFIG_PARSER_H
#define CONFIG_PARSER_H

#include <stdlib.h>

#include "config/config.h"

/** \file parser.h
  * \ingroup config
  * \brief Simple configuration parser
  * \author Ralf Kaestner
  * 
  * The parser interface allows for parsing parameter values for entire
  * configurations from command line arguments. It implements the concepts
  * of positional and non-positional arguments (called options), and
  * provides the possibility to group non-positional arguments for
  * re-usability in library projects.
  */

/** \name Parameters
  * \brief Predefined configuration parser parameters
  */
//@{
#define CONFIG_PARSER_PARAMETER_HELP              "help"
//@}

/** \name Constants
  * \brief Predefined configuration parser constants
  */
//@{
#define CONFIG_PARSER_HELP_WIDTH                  80
#define CONFIG_PARSER_HELP_HANG_INDENT            2
#define CONFIG_PARSER_HELP_KEY_INDENT             2
#define CONFIG_PARSER_HELP_PAR_INDENT             30
//@}

/** \name Error Codes
  * \brief Predefined configuration error codes
  */
//@{
#define CONFIG_PARSER_ERROR_NONE                  0
#define CONFIG_PARSER_ERROR_WRITE_MAN             1
#define CONFIG_PARSER_ERROR_ARGUMENT              2
#define CONFIG_PARSER_ERROR_ARGUMENT_MISSING      3
#define CONFIG_PARSER_ERROR_ARGUMENT_FORMAT       4
#define CONFIG_PARSER_ERROR_ARGUMENT_KEY          5
#define CONFIG_PARSER_ERROR_ARGUMENT_VALUE        6
//@}

/** \brief Predefined configuration parser error descriptions
  */
extern const char* config_parser_errors[];

/** \brief Predefined configuration parser default options
  */
extern config_t config_parser_default_options;

/** \brief Configuration parser
  */
typedef enum {
  config_parser_exit_never,     //!< Parser never terminates its process.
  config_parser_exit_error,     //!< Parser terminates in case of error.
  config_parser_exit_help,      //!< Parser terminates in case of help.
  config_parser_exit_both       //!< Parser terminates in case of error or help.
} config_parser_exit_t;

/** \brief Configuration parser option group structure
  */
typedef struct config_parser_option_group_t {
  config_t options;             //!< The parser option group's options.
  
  char prefix[128];             //!< The parser option group prefix.
  
  char summary[128];            //!< The parser option group summary.
  char description[1024];       //!< The parser option group description.
} config_parser_option_group_t, *config_parser_option_group_p;

/** \brief Configuration parser structure
  */
typedef struct config_parser_t {
  config_t arguments;           //!< The positional parser arguments.
  config_t options;             //!< The non-positional parser options.
  
  config_parser_option_group_p option_groups; //!< The parser option groups.
  size_t num_option_groups;     //!< The number of parser option groups.
  
  char summary[128];            //!< The configuration parser summary.
  char description[1024];       //!< The configuration parser description.
  
  char command[256];            //!< The command running the parser.
  char usage[512];              //!< The usage line generated by the parser.
  
  int error;                    //!< The error produced during parsing.
  char error_what[256];         //!< What produced the parsing error.
} config_parser_t, *config_parser_p;

/** \brief Initialize a configuration parser
  * \param[in] parser The configuration parser to be initialized.
  * \param[in] arguments An optional configuration used to initialize the
  *   positional parser arguments.
  * \param[in] options An optional configuration used to initialize the
  *   non-positional parser options.
  * \param[in] summary An optional, short summary describing the command
  *   which is running the parser.
  * \param[in] description An optional, long description of the command
  *   which is running the parser.
  */
void config_parser_init(
  config_parser_p parser,
  config_p arguments,
  config_p options,
  const char* summary,
  const char* description);

/** \brief Initialize a configuration parser from default options
  * \param[in] parser The configuration parser to be initialized.
  * \param[in] summary An optional, short summary describing the command
  *   which is running the parser.
  * \param[in] description An optional, long description of the command
  *   which is running the parser.
  */
void config_parser_init_default(
  config_parser_p parser,
  const char* summary,
  const char* description);

/** \brief Destroy a configuration parser
  * \param[in] parser The configuration parser to be destroyed.
  */
void config_parser_destroy(
  config_parser_p parser);

/** \brief Add an option group to the configuration parser
  * \param[in] parser The configuration parser to which the option group
  *   will be added.
  * \param[in] options The options to be assigned to the option group, can
  *   be null in which case the added option group will be empty.
  * \param[in] prefix An optional prefix of the parser option group.
  * \param[in] summary An optional, short summary of the parser option group.
  * \param[in] description An optional, long description of the parser option
  *   group.
  * \return The option group added to the configuration parser.
  */
config_parser_option_group_p config_parser_add_option_group(
  config_parser_p parser,
  config_p options,
  const char* prefix,
  const char* summary,
  const char* description);

/** \brief Parse command line arguments
  * \param[in,out] parser The configuration parser used to parse the
  *   command line arguments. Its configuration will be updated from the
  *   values supplied by positional and non-positional arguments.
  * \param[in] argc The number of supplied command line arguments.
  * \param[in] argv The list of supplied command line arguments.
  * \param[in] exit The exit policy of the parser in case of an error
  *   or help request. If an error occurred and the parser should exit
  *   on errors, usage information will be printed to stderr before
  *   terminating the calling process with a non-zero value. If help is
  *   requested and the parser is asked to exit on help requests, the help
  *   text will be printed to stdout and the calling process will terminate
  *   with a zero result.
  * \return The resulting error code.
  */
int config_parser_parse(
  config_parser_p parser,
  int argc,
  char** argv,
  config_parser_exit_t exit);

/** \brief Print usage information for a configuration parser
  * \note This is a convenience function which may be used to generate
  *   textual usage information according to a parser's configuration.
  *   It is commonly called after a failure to parse the command line.
  * \param[in] stream The output stream that will be used for printing the
  *   usage information.
  * \param[in] parser The configuration parser for which the usage
  *   information will be printed.
  */
void config_parser_print_usage(
  FILE* stream,
  config_parser_p parser);

/** \brief Print help text for a configuration parser
  * \note This is a convenience function which may be used to generate
  *   textual help according to a parser's configuration.
  * \param[in] stream The output stream that will be used for printing the
  *   help text.
  * \param[in] parser The configuration parser for which the help text
  *   will be printed.
  */
void config_parser_print_help(
  FILE* stream,
  config_parser_p parser);

/** \brief Write manual page for a configuration parser
  * \note This is a convenience function which may be used to generate
  *   Linux manual pages according to a parser's configuration.
  * \param[in] filename The name of the manual page file to be written.
  *   The special filename '-' indicates that the manual page shall be
  *   written to stdout.
  * \param[in] parser The configuration parser for which the manpage
  *   will be written.
  * \return The resulting error code.
  */
int config_parser_write_man(
  const char* filename,
  config_parser_p parser);

#endif
